export const FETCH_POSTS_FOLLOWING = "FETCH_POSTS_FOLLOWING";
export const FETCH_POSTS_FOLLOWING_SUCCESS = "FETCH_POSTS_FOLLOWING_SUCCESS";
export const FETCH_POSTS_FOLLOWING_FAIL = "FETCH_POSTS_FOLLOWING_FAIL";

export const GET_DETAIL_POST = "GET_DETAIL_POST";
export const GET_DETAIL_POST_SUCCESS = "GET_DETAIL_POST_SUCCESS";
export const GET_DETAIL_POST_FAIL = "GET_DETAIL_POST_FAIL";

export const LIKE_POST = "LIKE_POST";
export const LIKE_POST_SUCCESS = "LIKE_POST_SUCCESS";
export const LIKE_POST_FAIL = "LIKE_POST_FAIL";

export const CREATE_POST = "CREATE_POST";
export const CREATE_POST_SUCCESS = "CREATE_POST_SUCCESS";
export const CREATE_POST_FAIL = "CREATE_POST_FAIL";
