export const ADD_AVATAR = "ADD_AVATAR";
export const ADD_AVATAR_SUCCESS = "ADD_AVATAR_SUCCESS";
export const ADD_AVATAR_FAIL = "ADD_AVATAR_FAIL";

export const UPDATE_PROFILE = "UPDATE_PROFILE";
export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS";
export const UPDATE_PROFILE_FAIL = "UPDATE_PROFILE_FAIL";

export const CHANGE_PASSWORD = "CHANGE_PASSWORD";
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS";
export const CHANGE_PASSWORD_FAIL = "CHANGE_PASSWORD_FAIL";

export const GET_PROFILE = "GET_PROFILE";
export const GET_PROFILE_SUCCESS = "GET_PROFILE_SUCCESS";
export const GET_PROFILE_FAIL = "GET_PROFILE_FAIL";

export const GET_PROFILE_USER = "GET_PROFILE_USER";
export const GET_PROFILE_USER_SUCCESS = "GET_PROFILE_USER_SUCCESS";
export const GET_PROFILE_USER_FAIL = "GET_PROFILE_USER_FAIL";

export const FOLLOW = "FOLLOW";
export const FOLLOW_SUCCESS = "FOLLOW_SUCCESS";
export const FOLLOW_FAIL = "FOLLOW_FAIL";

export const GET_FOLLOWING = "GET_FOLLOWING";
export const GET_FOLLOWING_SUCCESS = "GET_FOLLOWING_SUCCESS";
export const GET_FOLLOWING_FAIL = "GET_FOLLOWING_FAIL";

export const GET_FOLLOWING_USER = "GET_FOLLOWING_USER";
export const GET_FOLLOWING_USER_SUCCESS = "GET_FOLLOWING_USER_SUCCESS";
export const GET_FOLLOWING_USER_FAIL = "GET_FOLLOWING_USER_FAIL";

export const GET_FOLLOWER_USER = "GET_FOLLOWER_USER";
export const GET_FOLLOWER_USER_SUCCESS = "GET_FOLLOWER_USER_SUCCESS";
export const GET_FOLLOWER_USER_FAIL = "GET_FOLLOWER_USER_FAIL";

export const SEARCH = "SEARCH";
export const SEARCH_SUCCESS = "SEARCH_SUCCESS";
